### ISSUE TITLE
There's no way to actually import redis as a transport as stated in the docs

### ISSUE THREAD

**Issue by kilobyte2007** [adonisjs/transmit#10]
### Package version

0.4.1

### Describe the bug

The docs specify that I can import redis as a transport like this:
```ts
import { redis } from '@adonisjs/transmit/transports'
```

but there's no such export in the transmit package. Is this a documentation mistake?

Also in another example, redis is imported like this (which is also not working):
```ts
import { defineConfig, redis } from '@adonisjs/transmit'
```

**Comment by kilobyte2007** [comment]
Made it work by importing it like this, but it's probably a mistake in the build process:
```ts
import { redis } from '@rlanz/bus/drivers/redis'
```

**Comment by RomainLanz** [comment]
Hey @kilobyte2007! 👋🏻 

What version are you running?

**Comment by kilobyte2007** [comment]
Hi @RomainLanz ,

It doesn't work and when I look at the source code there's indeed no such export. Seems to me like the `transmits.ts` file is not bundled.

You can see here that the `transmits.ts` file is not in the bundle - https://www.npmjs.com/package/@adonisjs/transmit

**Comment by kilobyte2007** [comment]
That was quick! 
Works like a charm, thanks a lot!

**Comment by RomainLanz** [comment]
Cool! Let me know if you have any other issue or question!

**Comment by kilobyte2007** [comment]
I do have one but I will open a separate issue for that one.
