### ISSUE TITLE
Ping interval on shutdown on cleared on shutdown

### ISSUE THREAD

**Issue by adrianNEMO** [adonisjs/transmit#12]
### Package version

0.4.1

### Describe the bug

The ping interval is not being cleared on shutdown. This prevents Adonis to shutdown e.g. when running tests.

**Comment by RomainLanz** [comment]
Hey @adrianNEMO! 👋🏻 

Yes, I noted this in my mind but forgot it. lol. 😅 
It will be fixed in a few hours. 👍🏻

**Comment by adrianNEMO** [comment]
Appreciated thanks!
