### ISSUE TITLE
Transmit doesn't work with domain setup

### ISSUE THREAD

**Issue by Steveperi** [adonisjs/transmit#16]
### Package version

adonis 6

### Describe the bug

I have the following error.
![Screenshot 2024-04-10 at 11 19 35 AM](https://github.com/adonisjs/transmit/assets/6014414/56529b6a-5478-44cb-a30c-e385dd4ae745)

When I setup the route with this code 
```
router.get('/', '#controllers/sites_controller.index').domain(process.env.SITE_DOMAIN!)
```
 transmit doesn't work, but it works when remove 
```
.domain(process.env.SITE_DOMAIN!)
```

Here is the repository [repo](https://github.com/Steveperi/adonis-transmit) where can you reproduce the problem.

Thank you 

### Reproduction repo

https://github.com/Steveperi/adonis-transmit

**Comment by RomainLanz** [comment]
Can you try with [`v0.5.2`](https://github.com/adonisjs/transmit/releases/tag/v0.5.2)?

**Comment by Steveperi** [comment]
> Can you try with [`v0.6.0`](https://github.com/adonisjs/transmit/releases/tag/v0.6.0)?
> 
> You can now customize the route registration inside the `config/transmit.ts` file.

Hello

I updated the package to v.0.6.0 but not working. I have the same error.

**Comment by RomainLanz** [comment]
Have you changed the configuration to use your custom domain as shared in the release note?

**Comment by Steveperi** [comment]
> Have you changed the configuration to use your custom domain as shared in the release note?

I'm sorry my mistake. It works for one domain. My app has multiple domains, how can I do that?

**Comment by RomainLanz** [comment]
You wont have multiple Transmit endpoint, choose one and stick with it. In your case, you should select the TLD `localhost` since all others will be able to access it.

**Comment by Steveperi** [comment]
> You wont have multiple Transmit endpoint, choose one and stick with it. In your case, you should select the TLD `localhost` since all others will be able to access it.

Ok I thought that and I tried it, but from client side I have cors errors.

**Comment by RomainLanz** [comment]
This is something you have to fix in your side, it is not related to Transmit.

**Comment by Steveperi** [comment]
> This is something you have to fix on your side; it is not related to Transmit.

Ok, but I think is related to the transmit client package. I'll try to make it work.

Thank you for your time
