### ISSUE TITLE
Transmit doesn't work with CSRF enabled

### ISSUE THREAD

**Issue by nxtdv** [adonisjs/transmit#18]
### Package version

1.0.0

### Describe the bug

When CSRF is enabled (including enableXsrfCookie), the client is able to subscribe to the server, but logs indicate an invalid or expired CSRF token.

![image](https://github.com/adonisjs/transmit/assets/60948214/71b47977-e1d1-4f57-9434-ca87dc29976f)
![image](https://github.com/adonisjs/transmit/assets/60948214/51fc45fa-cc02-4901-838b-e44cb826520f)

Let me know if you need more information.

**Comment by RomainLanz** [comment]
Hey @nxtdv! 👋🏻 

Have you activated the `XsrfCookie` cookie option?

📚 https://docs.adonisjs.com/guides/web-security#config-reference

**Comment by nxtdv** [comment]
Thank you sm 🙌

That should work better!
