### ISSUE TITLE
Silent auth middleware usage in RouteHandlerModifier config property

### ISSUE THREAD

**Issue by leytonlyy** [adonisjs/transmit#20]
### Package version

1.0.0

### Describe the bug

I'm trying to use the silent auth middleware in the RouteHandlerModifier property when configuring transmit but when i do so the app crashes on boot.
I cloned the ['Transmit-demo'](https://github.com/RomainLanz/transmit-demo) repository and added the code stated in the docs in the ``config/transmit.ts`` file:

```typescript
import { defineConfig } from '@adonisjs/transmit'
import { middleware } from '#start/kernel'

export default defineConfig({
  routeHandlerModifier(route) {
    if (route.getPattern() === '/__transmit/events') {
      route.middleware(middleware.auth())
      return
    }
  }
})
```

This is the error i get:
```sepolicy
   TypeError: Cannot read properties of undefined (reading 'errorHandler')
 
   at <anonymous> start/kernel.ts:18
   13|  
   14|  /**
   15|   * The error handler is used to convert an exception
   16|   * to a HTTP response.
   17|   */
 ❯ 18|  server.errorHandler(() => import('#exceptions/handler'))
   19|  
   20|  /**
   21|   * The server middleware stack runs middleware on all the HTTP
   22|   * requests, even if there is no route registered for
   23|   * the request URL.
```

It appears that interacting with the middleware within the  makes the app crash:
```typescript
import { middleware } from '#start/kernel'
import { defineConfig } from '@adonisjs/transmit'

export default defineConfig({
  pingInterval: false,
  transport: null,
  routeHandlerModifier(route) {
    if (route.getPattern() === '/__transmit/events') {
      console.log(middleware)
      return
    }
  },
})
``` 
Generates the same error.

### Reproduction repo

https://github.com/RomainLanz/transmit-demo/

**Comment by RomainLanz** [comment]
Hey @leytonlyy! 👋🏻 

Can you try the same while important the `middleware` stack inside the `routeHandlerModifier` function?

```ts
import { defineConfig } from '@adonisjs/transmit'

export default defineConfig({
  pingInterval: false,
  transport: null,
  async routeHandlerModifier(route) {
    const { middleware } = await import('#start/kernel')
    
    if (route.getPattern() === '/__transmit/events') {
      console.log(middleware)
      return
    }
  },
})
```

**Comment by leytonlyy** [comment]
Hi @RomainLanz, it worked thank you ! Do you know why it is happening ?

Also noticed that ``getPattern`` method returns the route pattern as ``__transmit/events`` instead of  ``/__transmit/events`` as stated in the documentation of transmit

**Comment by RomainLanz** [comment]
Documentation has been updated. 👍🏻
