### ISSUE TITLE
Add channel name scoping for different environments

### ISSUE THREAD

**Issue by sivo1981** [adonisjs/transmit#21]
### Package version

@adonisjs/transmit@1.0.0

### Describe the bug

Is it possible to include some kind of channel name scoping when using Redis as transport provider. When using same Redis instance all environments receive event from Pub/sub.

**Comment by RomainLanz** [comment]
Hey @sivo1981?

Could you please elaborate on what you mean by "channel name scoping"?

**Comment by sivo1981** [comment]
Application with same code base is runing in two different environments "production" and "test". Using channel name lets say "users" and transmit transport Redis with connection to the same server instance it will result in sending events on both environments because redis pub/sub doesn't care about this, it just sends event to all clients subscribed to this channel.

This is also stated here: [https://redis.io/docs/latest/develop/interact/pubsub/](url)

Probably it would be the best options to prefix channel names based on some env variable so the final channel name would be `${CHANNEL_PREFIX}_users`. This is already implemented for `@adonisjs/redis` package via `REDIS_PREFIX` for example.

**Comment by RomainLanz** [comment]
You can define a `keyPrefix` in the configuration of the Transport, would that fix your issue?

```ts
import env from '#start/env'
import { defineConfig } from '@adonisjs/transmit'
import { redis } from '@adonisjs/transmit/transports'

export default defineConfig({
  transport: {
    driver: redis({
      host: env.get('REDIS_HOST'),
      port: env.get('REDIS_PORT'),
      password: env.get('REDIS_PASSWORD'),
      keyPrefix: 'transmit',
    })
  }
})
```

 📚  https://docs.adonisjs.com/guides/digging-deeper/transmit#configuration

**Comment by sivo1981** [comment]
Yes, this would solve my issue if implementation would work also for channel names scoping. Currently it works only for storing keys.

**Comment by RomainLanz** [comment]
Correct! I will update the code accordingly to use the `keyPrefix` set for our broadcasting channels.

**Comment by RomainLanz** [comment]
You can change the channel per application using the `channel` property inside the Transmit configuration. I have to document it since it seems missing.

```ts
export default defineConfig({
  transport: {
    channel: 'xxx',
    driver: redis({
      host: env.get('REDIS_HOST'),
      port: env.get('REDIS_PORT'),
      password: env.get('REDIS_PASSWORD'),
      keyPrefix: 'transmit',
    })
  }
})
```

This will allow you to have a different channel per application.
Does that fix your issue?

**Comment by sivo1981** [comment]
Yes, this works perfect.
