### ISSUE TITLE
Broadcastable type doesn't support array

### ISSUE THREAD

**Issue by EvanPerreau** [adonisjs/transmit#23]
### Package version

1.0.1

### Describe the bug

![image](https://github.com/adonisjs/transmit/assets/114474918/06827ef1-99b1-41e8-bd33-a4075c4e6b44)
the type Broadcastable doesn't support array

**Comment by RomainLanz** [comment]
Hey @EvanPerreau! 👋🏻 

It seems to be a type issue. Can you confirm if the code works despite the typing error?

**Comment by EvanPerreau** [comment]
Hello @RomainLanz,

Thanks for your reactivity. Yes, the code works perfectly except for the type error. Currently, I am using the `//@ts-ignore` annotation to avoid the type error. I am trying to pass an array in the transmit broadcast in a simple chat app, and it works perfectly ;)

It would be great if you could patch the bug. If you want, I can patch the bug and make a pull request to this repo.

**Comment by EvanPerreau** [comment]
I fix this bug in the pull request #24 ;)
