### ISSUE TITLE
transmit authorization always fail

### ISSUE THREAD

**Issue by EvanPerreau** [adonisjs/transmit#25]
### Package version

1.0.2

### Describe the bug

Hello, I have a huge problem with the transmit authorization, I have a authorization for a channel : 

![image](https://github.com/adonisjs/transmit/assets/114474918/cca61271-7031-44de-8339-a318b3091466)

with this policy (the policy always return true for debug)

![image](https://github.com/adonisjs/transmit/assets/114474918/8be13db7-4ff0-458f-998c-9fde8727dfd5)

when i try to connect my front end to the channel

![image](https://github.com/adonisjs/transmit/assets/114474918/7d80fb73-de53-437f-8dba-86b11e01d2a4)

but if I directly return true in the channel auth config :

![image](https://github.com/adonisjs/transmit/assets/114474918/0ff6ea80-a35a-4cc1-a74a-1877e6db5303)

it work 🙃

![image](https://github.com/adonisjs/transmit/assets/114474918/5445f72e-fb72-4a3c-8241-ad35b496a389)

**Comment by RomainLanz** [comment]
Hey @EvanPerreau! 👋🏻 

Could you please provide a repository with the minimum amount of code to reproduce your issue?
As per the Transmit codebase, it should work fine.

**Comment by EvanPerreau** [comment]
Hey @RomainLanz , 
I guess this error is throw becasue i don't config the routeHandleModifier in transmit config.
But, a new error appear :
![image](https://github.com/adonisjs/transmit/assets/114474918/4f619ca8-54e1-4b3f-850e-d842e51cc66c)
![image](https://github.com/adonisjs/transmit/assets/114474918/2af19ba0-7677-4840-b0eb-67562898c2f3)

**Comment by RomainLanz** [comment]
Are you sure you are not importing the kernel at the top of your file too?

**Comment by EvanPerreau** [comment]
@RomainLanz 
it's my transmit.ts config file:

![image](https://github.com/adonisjs/transmit/assets/114474918/9845821f-afba-4c95-ac03-2af1390a2a43)

and my kernel.ts file :
![image](https://github.com/adonisjs/transmit/assets/114474918/6e07a3be-8c3d-48fd-a0b0-fe430ce962ba)

**Comment by LoicOuth** [comment]
Hi @EvanPerreau 

I found a workaround. You can call auth.check() before checking if the user ID is equal to the channel ID.

`transmit.authorizeChannel<{ id: string }>(
  'users/:id/notifications',
  async (ctx: HttpContext, { id }) => {
    await ctx.auth.check()
    return ctx.auth.user?.id === +id
  }
)`

**Comment by RomainLanz** [comment]
You can notice that you are importing the middleware at the top of your file instead of in the callback.
Please, check the documentation again.

📚  https://docs.adonisjs.com/guides/digging-deeper/transmit#configuration

**Comment by EvanPerreau** [comment]
@RomainLanz I also have the error when I import middleware in the callback like the doc :
![image](https://github.com/adonisjs/transmit/assets/114474918/db152dfe-529c-4fa3-8b0d-13260ba47d07)

![image](https://github.com/adonisjs/transmit/assets/114474918/958cc40a-f3d5-40e3-b644-7f85ea01e8ee)

**Comment by EvanPerreau** [comment]
server is undefined

**Comment by RomainLanz** [comment]
That's weird, but let me devise a new way to modify the route. It will solve this issue.

Related: https://github.com/adonisjs/transmit/issues/26

**Comment by EvanPerreau** [comment]
@RomainLanz ok tank's

**Comment by EvanPerreau** [comment]
hey @RomainLanz, some good news about your modifications to solve this issue ?

**Comment by RomainLanz** [comment]
Hey @EvanPerreau! 👋🏻 

Could you please try to install `@adonisjs/transmit@next` and add the following code to your route file:

```ts
import transmit from '@adonisjs/transmit/services/main'

transmit.registerRoute(() => {
  // Your route's customization code here
})
```

**Comment by RomainLanz** [comment]
Did you have the chance to try the new version? Do you have any feedback or issues before I make a final release?

**Comment by EvanPerreau** [comment]
Hello,  try to use the new version but I was not convinced, i switch to WebSocket
