### ISSUE TITLE
Authorizing channels doesn't work

### ISSUE THREAD

**Issue by radudalbea** [adonisjs/transmit#30]
### Package version

latest

### Describe the bug

transmit.authorizeChannel<{ id: string }>('users/:id', (ctx: HttpContext, { id }) => {
  return ctx.auth.user?.id === +id
})

the ctx.auth is undefined so you cannot authorize clients. I don't know if we need to add the auth middleware but in the documentation is nothing about it.

**Comment by RomainLanz** [comment]
Hey @radudalbea! 👋🏻 

Have you installed the auth module of AdonisJS?

**Comment by radudalbea** [comment]
Hey @RomainLanz 

yes I did. you can test this with the most basic adonis setup with auth and transmit. 

the only solution I have found to make this work is to override the transmit provider boot method, call my provider instead of the package one and to register the routes myself attaching the auth middleware.

```
router
  .group(() => {
    router.get('__transmit/events', (ctx) => {
      transmit.$createStream(ctx);
    });

    router.post('__transmit/subscribe', (ctx) => {
      const uid = ctx.request.input('uid');
      const channel = ctx.request.input('channel');
      const success = transmit.$subscribeToChannel(uid, channel, ctx);

      if (!success) {
        return ctx.response.badRequest();
      }

      return ctx.response.noContent();
    });

    router.post('__transmit/unsubscribe', (ctx) => {
      const uid = ctx.request.input('uid');
      const channel = ctx.request.input('channel');

      const success = transmit.$unsubscribeFromChannel(uid, channel, ctx);

      if (!success) {
        return ctx.response.badRequest();
      }

      return ctx.response.noContent();
    });
  })
  .use(middleware.auth());
```

Also the documentation is kind of confusing. For example there is this: https://docs.adonisjs.com/guides/digging-deeper/transmit#register-routes that says that you can register routes with transmit.registerRoutes() but this method doesn't exist. 

Thanks,
Radu

**Comment by RomainLanz** [comment]
What version of Transmit are you using?

**Comment by radudalbea** [comment]
"@adonisjs/transmit": "^0.4.2",

**Comment by radudalbea** [comment]
So I see that the latest version on git is 2.0.2 but I have installed the package using the official documentation so 
`node ace add @adonisjs/transmit` and the funny thing is that I have installed it last week. I did it again right now and it seems that the installer gets version 0.4.2

**Comment by radudalbea** [comment]
I have figure it out. It was from my node version. for the latest transmit version you need node 20.11.1 while I had 20.10.

The official framework documentations says: Before creating a new application, you should ensure that you have Node.js and npm installed on your computer. AdonisJS needs Node.js >= 20.6. 

I will test with this version and let you know if it works.

**Comment by RomainLanz** [comment]
That's probably a mistake on my side. I don't remember using any feature that requires 20.11.
I will double-check that and update the library accordingly.

**Comment by radudalbea** [comment]
Hei @RomainLanz 

I have tested version 2.0.2 and it works but you need to change the documentation with the following:

1. `transmit.authorizeChannel` is `now transmit.authorize`
2. for authorizing channels users need to to something like 
```
transmit.registerRoutes((route) => {
  route.middleware([middleware.auth()]);
});
```

Thanks for the help and great job with all these packages.

**Comment by RomainLanz** [comment]
The documentation is already up to date with the new version; you may have read the article instead, which was written when V1 was around.

Closing since your issue is fixed, enjoy using AdonisJS! 🙌🏻
