### ISSUE TITLE
Gzip on the server was stopping Transmit from working

### ISSUE THREAD

**Issue by eduwass** [adonisjs/transmit#31]
### Package version

2.0.2

### Bug Report: Gzip Interference with Adonis Transmit/Client on Coolify Deployment

**Description:**

I'm new to Adonis and encountered an issue when deploying Adonis with Transmit (`@adonisjs/transmit` v2.0.2) and Transmit Client (`@adonisjs/transmit-client` v1.0.0) packages on a Hetzner VPS via Coolify. The setup works perfectly on my local machine but fails after deployment. I'm not entirely sure if this is a bug, but I wanted to report it in case others experience the same issue.

**Environment:**
- **Adonis Version**: 6.13.1
- **Transmit Version**: 2.0.2
- **Transmit Client Version**: 1.0.0
- **VPS Provider**: Hetzner
- **Deployment Platform**: Coolify

**Steps to Reproduce:**
1. Install Adonis and add Transmit and Transmit Client packages.
2. Deploy the app to a Hetzner VPS via Coolify.
4. Observe the failure.

**Expected Behavior:**
Transmit should work as expected after deployment, similar to the local environment.

**Actual Behavior:**
- The `__transmit/subscribe` HTTP request is missing in production. For example, accessing `http://localhost:3333/__transmit/subscribe` does not work in production.
- The `__transmit/events?uid=xxx` request in production does not get a `200 OK` response.
- As a result, the connection is never successfully established.

**Workaround:**
Disabling Gzip in Coolify (an option in the Coolify dashboard) resolved the problem.

**Additional Information:**
Since I'm new to Adonis, I’m not sure if this is a bug or a configuration issue. I'm happy to provide more details or logs if necessary.

If it's an actual configuration issue, I think adding this to the documentation for future users would be a good addition.

Thanks for the awesome work!

**Comment by RomainLanz** [comment]
Hey @eduwass! 👋🏻 

This is interesting! Do you know which Reverse Proxy Coolify is setting up on your server?

Also, do you have any logs on your server that may explain why `__transmit/events` never answer? It should answer and keep the connection open.

I needed to add a few headers to make it work properly with `Traefik` and `Nginx`, so it may be something on our side.

**Comment by eduwass** [comment]
Hi @RomainLanz 👋 

Thanks for chiming in so quickly!

I believe Coolify does set up a reverse proxy using Traefik to manage traffic, here's a Configuration file I've found:

```
networks:
  coolify:
    external: true
services:
  traefik:
    container_name: coolify-proxy
    image: 'traefik:v3.1'
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - coolify
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    healthcheck:
      test: 'wget -qO- http://localhost:80/ping || exit 1'
      interval: 4s
      timeout: 2s
      retries: 5
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/data/coolify/proxy:/traefik'
    command:
      - '--ping=true'
      - '--ping.entrypoint=http'
      - '--api.dashboard=true'
      - '--api.insecure=false'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.https.address=:443'
      - '--entrypoints.http.http.encodequerysemicolons=true'
      - '--entryPoints.http.http2.maxConcurrentStreams=50'
      - '--entrypoints.https.http.encodequerysemicolons=true'
      - '--entryPoints.https.http2.maxConcurrentStreams=50'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.file.directory=/traefik/dynamic/'
      - '--providers.file.watch=true'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge=true'
      - '--certificatesresolvers.letsencrypt.acme.storage=/traefik/acme.json'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http'
      - '--providers.docker=true'
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - coolify.managed=true
```

Regarding the request, my server logs were showing a completed HTTP request, but it didn't show up as completed in the browser:

```
[14:13:45.505] INFO (140): Completed HTTP request
    method: "GET"
    url: "/__transmit/events"
    requestHeaders: {
      "host": "gzip.sp500.info",
      "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Safari/605.1.15",
      "accept": "application/json",
      "accept-encoding": "gzip, deflate, br",
      "accept-language": "en-US,en;q=0.9",
      "cache-control": "no-cache",
      "cookie": "adonis-session=s%3AeyJtZXNzYWdlIjoieXBsZnMxM240d3hlZmprYXVmMXR5ZzFwIiwicHVycG9zZSI6ImFkb25pcy1zZXNzaW9uIn0.YVWZnXsjdstZqEyUwFCY08vzmfqyFk4n-5IizkfkoPk",
      "pragma": "no-cache",
      "priority": "u=3, i",
      "referer": "https://gzip.sp500.info/",
      "sec-fetch-dest": "empty",
      "sec-fetch-mode": "cors",
      "sec-fetch-site": "same-origin",
      "x-forwarded-for": "194.158.70.13",
      "x-forwarded-host": "gzip.sp500.info",
      "x-forwarded-port": "443",
      "x-forwarded-proto": "https",
      "x-forwarded-server": "5ef697d65c1a",
      "x-real-ip": "194.158.70.13",
      "x-request-id": "txrc88ky54xj8tix998i8hsq"
    }
    requestBody: {}
    responseHeaders: {
      "set-cookie": "adonis-session=s%3AeyJtZXNzYWdlIjoieXBsZnMxM240d3hlZmprYXVmMXR5ZzFwIiwicHVycG9zZSI6ImFkb25pcy1zZXNzaW9uIn0.YVWZnXsjdstZqEyUwFCY08vzmfqyFk4n-5IizkfkoPk; Max-Age=7200; Path=/; HttpOnly; Secure; SameSite=Lax"
    }
    status: 200
    responseTime: 2.27261
    clientIp: "172.18.0.3"
    queryString: {
      "uid": "d0585165-e6b7-4227-a5e0-18248afcee4e"
    }
    routeParams: {}
    acceptedTypes: [
      "application/json"
    ]
    operation: "completed_http_request"
    file: "app/build/app/middleware/log_request.js"
    function: "LogRequest.handle"
```

The moment I disabled Gzip in the Coolify UI, this option here:
![000216@2x](https://github.com/user-attachments/assets/2878b373-b583-4655-a553-4abed91c00f0)

The request started successfully responding. 

I've deployed two instances of the same project with and without gzip to be able to easily see the difference in behavior:
- https://sp500.info
- https://gzip.sp500.info

If you open up network tab on the gzip one you'll see how /events is not resolving.

**Comment by RomainLanz** [comment]
Can you try to monkeypatch the `@boringnode/transmit` module and add `Content-Encoding: deflate` in the header sent?

**Comment by eduwass** [comment]
Hi @RomainLanz 👋,

Thanks again for the guidance earlier!

I apologize for the late reply, I went away on a long vacation and I've just got back recently.

Had a chance to tackle this again today, here's an update on what I've tried so far:

1. I manually patched the `@boringnode/transmit` module by adding the `Content-Encoding: deflate` header to the `destination.writeHead` method in `stream.js`.
2. After applying the patch and restarting the server, the `Content-Encoding` header is now correctly added to the response for the `/__transmit/events` endpoint.
3. However, I’m observing a new behavior: the SSE connection frequently disconnects and reconnects. This pattern is consistent, and it wasn’t happening prior to adding the `Content-Encoding: deflate` header.

You can see it right now in that test env: https://gzip.sp500.info

I wanted to check if you have any suggestions for debugging this behavior.

Looking forward to your thoughts!

Thanks again,  
Edu

**Comment by RomainLanz** [comment]
Here's my last suggestion: if this doesn't resolve the issue, I'll try reproducing it locally.

Could you update your Traefik configuration to use the [excludedcontenttypes setting](https://doc.traefik.io/traefik/middlewares/http/compress/#excludedcontenttypes) so that `text/event-stream` is not compressed?

**Comment by eduwass** [comment]
Hi @RomainLanz 

You nailed it, after playing around with the Traefik config it seems like it is now working!

<details><summary>Final Config</summary>
<p>

![Safari 2024-12-09 16 01 55](https://github.com/user-attachments/assets/ae93fdcd-9a4f-4705-849e-7fcbbfb70807)


```
traefik.enable=true
# Define a scoped middleware for gzip with excluded content types
traefik.http.middlewares.gzip-specific.compress=true
traefik.http.middlewares.gzip-specific.compress.excludedcontenttypes=text/event-stream

# Redirect HTTP traffic to HTTPS
traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https

# HTTP Router
traefik.http.routers.http-0-n40k0okosgggwo0ws0o0g48k.entryPoints=http
traefik.http.routers.http-0-n40k0okosgggwo0ws0o0g48k.middlewares=redirect-to-https
traefik.http.routers.http-0-n40k0okosgggwo0ws0o0g48k.rule=Host(`gzip.sp500.info`) && PathPrefix(`/`)
traefik.http.routers.http-0-n40k0okosgggwo0ws0o0g48k.service=http-0-n40k0okosgggwo0ws0o0g48k

# HTTPS Router with scoped gzip middleware
traefik.http.routers.https-0-n40k0okosgggwo0ws0o0g48k.entryPoints=https
traefik.http.routers.https-0-n40k0okosgggwo0ws0o0g48k.middlewares=gzip-specific
traefik.http.routers.https-0-n40k0okosgggwo0ws0o0g48k.rule=Host(`gzip.sp500.info`) && PathPrefix(`/`)
traefik.http.routers.https-0-n40k0okosgggwo0ws0o0g48k.service=https-0-n40k0okosgggwo0ws0o0g48k
traefik.http.routers.https-0-n40k0okosgggwo0ws0o0g48k.tls.certresolver=letsencrypt
traefik.http.routers.https-0-n40k0okosgggwo0ws0o0g48k.tls=true

# Service definitions
traefik.http.services.http-0-n40k0okosgggwo0ws0o0g48k.loadbalancer.server.port=3333
traefik.http.services.https-0-n40k0okosgggwo0ws0o0g48k.loadbalancer.server.port=3333

# Caddy-specific settings (unchanged)
caddy_0.encode=zstd gzip
caddy_0.handle_path.0_reverse_proxy={{upstreams 3333}}
caddy_0.handle_path=/*
caddy_0.header=-Server
caddy_0.try_files={path} /index.html /index.php
caddy_0=https://gzip.sp500.info
caddy_ingress_network=coolify
```

</p>
</details> 


Thanks so much for helping me debug this!

**Comment by eduwass** [comment]
PS: What do you think about adding a note about this here?
https://github.com/adonisjs/v6-docs/blob/main/content/docs/digging_deeper/transmit.md

And maybe in the [@adonisjs/transmit](https://github.com/adonisjs/transmit) readme too?

Happy to submit a PR for it if you like.

Thanks!

**Comment by RomainLanz** [comment]
Yes, we can update the documentation to mention GZip and clarify that it should be disabled for the `text/event-stream` content type.

We can also include an example with a Traefik configuration.

Could you open a PR to update the documentation, this repository’s README, and the README within the BoringNode organization?

**Comment by eduwass** [comment]
Here you go @RomainLanz :

- https://github.com/adonisjs/v6-docs/pull/174
- https://github.com/adonisjs/transmit/pull/35
- https://github.com/boringnode/transmit/pull/1

**Comment by RomainLanz** [comment]
Great! Thanks for your help! 🙌🏻 
I am closing this issue.
