### ISSUE TITLE
Broadcastable type doesnt support Class instances

### ISSUE THREAD

**Issue by AminGtt** [adonisjs/transmit#32]
### Package version

2.0.2

### Describe the bug

It looks like instances of any of my Classes returns a type error; 
<img width="644" alt="issue_transmit_adonis" src="https://github.com/user-attachments/assets/c18ea9d7-5007-4832-b6c6-d942631f815c">

As seen in a previous issue, yes despite the type error the code works without problem.

**Comment by RomainLanz** [comment]
Hey @AminGtt! 👋🏻

This behavior is actually intentional. By default, JavaScript attempts to serialize your class using the `toJSON` method. This is why it might seem to work, but to avoid any unexpected issues, it's best to explicitly serialize it yourself before broadcasting.

**Comment by AminGtt** [comment]
Hey @RomainLanz! 
Thanks for your quick reply, works great now! Maybe it would be nice to add it to the doc?
