### ISSUE TITLE
Does not work with `csrf` enabled

### ISSUE THREAD

**Issue by Barbapapazes** [adonisjs/transmit#9]
### Package version

^0.2.3

### Describe the bug

Once you enabled the `shield.csrf` protection, client is unable to subscribe to the server.

**Comment by Barbapapazes** [comment]
could solve my issue: https://github.com/adonisjs/transmit-client/issues/2

will try

**Comment by RomainLanz** [comment]
Have you activated the `enableXsrfCookie` option in `config/shield.ts`?

**Comment by Barbapapazes** [comment]
> could solve my issue: [adonisjs/transmit-client#2](https://github.com/adonisjs/transmit-client/issues/2)
> 
> will try

works fine!

**Comment by Barbapapazes** [comment]
> Have you activated the `enableXsrfCookie` option in `config/shield.ts`?

Yes, after reading the code source of tansmit-client and now, everything is ok!
